Verbose for access token

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -19,7 +19,7 @@ pipelines:
             - helm repo index .
             # Generate oauth access token which is 2 hours valid
             - export ACCESS_TOKEN=$(
-                curl -s -X POST -u "$CLIENT_ID:$CLIENT_SECRET" \
+                curl --verbose -s -X POST -u "$CLIENT_ID:$CLIENT_SECRET" \
                     https://bitbucket.org/site/oauth2/access_token \
                     -d grant_type=client_credentials -d scopes="repository"|
                     jq --raw-output '.access_token'
@@ -32,8 +32,10 @@ pipelines:
                 HTTP_STATUS=$(
                   curl --write-out '%{http_code}' -X POST -H "Authorization: Bearer ${ACCESS_TOKEN}" \
                      https://api.bitbucket.org/2.0/repositories/$BITBUCKET_REPO_OWNER/$BITBUCKET_REPO_SLUG/downloads "-F files=@$f ");
-              if [ ! $HTTP_STATUS -eq 201 ]; then
-                echo -e "\\e[36mINFO: Status: $HTTP_STATUS for file: $f\\e[0m";
-                echo -e "\\e[31m✖ Error: Could not be uploaded to https://api.bitbucket.org/2.0/repositories/$BITBUCKET_REPO_OWNER/$BITBUCKET_REPO_SLUG/downloads [Http Status: $HTTP_STATUS]"\\e[0m""; exit 1;
-              fi
+                if [ ! $HTTP_STATUS -eq 201 ]; then
+                  echo -e "\\e[36mINFO: Status: $HTTP_STATUS for file: $f\\e[0m";
+                  echo -e "\\e[31m✖ Error: Could not be uploaded to https://api.bitbucket.org/2.0/repositories/$BITBUCKET_REPO_OWNER/$BITBUCKET_REPO_SLUG/downloads [Http Status: $HTTP_STATUS]"\\e[0m""; exit 1;
+                else
+                  echo -e "\\e[32m✔ successfully uploaded: $f \\e[0m";
+                fi
               done
